### ISSUE TITLE
Suggestion: NVME SSD

### ISSUE THREAD

**Issue by JamesMRamm** [jfpelland/HardwareIcons#1]
Hey, I've been using your icons today to draw up the specs for some home servers in a network diagram. I wanted to distinguish the NVME drives from SSD/HDDs, so I modified one of the RAM images.

You're welcome to tidy it up and include it at some stage, if you wanted to. You might also be able to make enough space for the drive letters, by merging the middle two chip boxes.

![NVME](https://github.com/jfpelland/HardwareIcons/assets/105151517/dc6407a2-f101-4821-ba3d-9db055a954c6)

**Comment by jfpelland** [comment]
Thanks for the suggestion! I've been thinking about these, along with icons that look more like physical hard drives. I'm a little busy at the moment, but they'll be included in the next release.
